### ISSUE TITLE
Resizing, attaching and detaching volumes

### ISSUE THREAD

**Issue by lalvarezguillen** [ngine-io/ansible-collection-vultr#15]
Hi @resmo. Great job on this project! Sorely needed! Specially considering how bad Vultr's v1 API is.

I noticed that the project doesn't provide the ability to resize volumes, or attach/detach them from servers. I've implemented those features (and integration tests for them) in the following MR: https://github.com/ngine-io/ansible-collection-vultr/pull/14

I ran the integration tests for the new features against my Vultr account, and they work without issues.

Let me know what you think. All feedback welcome.

**Comment by resmo** [comment]
fixed with #14
