### ISSUE TITLE
Update Vultr API to v2

### ISSUE THREAD

**Issue by jdoss** [ngine-io/ansible-collection-vultr#17]
The [Vultr v1 API](https://www.vultr.com/api/v1/) is deprecated and it would be great to be able to use the v2 API.

https://www.vultr.com/news/Announcing-Vultr-API-v2/

**Comment by Lvl4Sword** [comment]
Is there a list of anything missing between v1 and v2?
If we can find out what needs added/what's been removed/etc, I wouldn't mind helping with this.

**Comment by Lvl4Sword** [comment]
Circling back to this after 5+ months. Any interest in this? ¯\\\_(ツ)\_/¯

**Comment by resmo** [comment]
Thanks for bringing this up, I plan to start working beginning September with the transition to v2. 

btw, any sponsoring would help to stay motivated.

**Comment by resmo** [comment]
Please follow #22 for updates about implementation of the v2 API.

**Comment by 4n70w4** [comment]
I found workaround: using terraform =)

**Comment by resmo** [comment]
Thank you very much for your contribution.

In the meantime, Vultr has deprecated the v1 API and we have been working with @vultr to re-implement the modules with the v2 API.  

Therefore, this collection is now in maintenance mode and we encourage you to contribute new feature now here https://github.com/vultr/ansible-collection-vultr/.
