### ISSUE TITLE
/v1/server/create API should be userdata, not user_data

### ISSUE THREAD

**Issue by SJReese** [ngine-io/ansible-collection-vultr#27]
The vultr API lists the parameter for user-data as 'userdata', not 'user_data'. Changes /plubins/modules/vultr_server.py to use the correct parameter name. Interestingly, the set_user_data API call already used the correct name.

**Comment by resmo** [comment]
fixed by #26, released in v1.1.1

**Comment by resmo** [comment]
Thanks!
